# Generated by Django 4.2.7 on 2026-05-07 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_candidate_form_fee_payment_bank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateTimeField()),
                ('position', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_letter', models.FileField(upload_to='offer_letters/')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidate_form')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
