# Generated by Django 4.2.7 on 2026-05-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_offer_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_form',
            name='refered',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
